name: developmiracle
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  shared_preferences: ^2.5.3
  p2p_chat:
    git:
      url: https://github.com/AnisimovTema/wave_p2p.git
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  url_launcher: ^6.1.7
  analyzer: ^6.7.0
  build_runner:

flutter:
  uses-material-design: true
  generate: true
